
SELECT  [CurrencyCode],[Name],[ModifiedDate] FROM [AdventureWorks2014].[Sales].[Currency]


/* 

What is a cursor?

Cursors are database objects used to manipulate data in a set on a row-by-row basis;
Cursors should be generally avoided in production servers as they consume resourses as we shall see.

*/

--EXAMPLE 1:  SETTING UP A CURSOR AND VIEWING THE RESULT

DECLARE CURRENCY CURSOR  --STEP 1: DECLARE A CURSOR - MEANING GIVE IT A NAME

FOR SELECT  [CurrencyCode],[Name],[ModifiedDate]  --STEP 2: USE THE KEY WORD FOR TO SET THE SELECT STATEMENT THAT THE CUROR IS GOING TO EXECUTE AGAINST
    FROM [AdventureWorks2014].[Sales].[Currency]

OPEN CURRENCY   --<< STEP 3: OPEN THE CURSOR TO POINT TO THE SELECT STATEMENT FIRST ROW

	FETCH NEXT FROM CURRENCY   --<< STEP 4:  BRINGS THE FIRST RECORD
	WHILE @@FETCH_STATUS  = 0  --<< STEP 5: SET THE @@FETCH_STATUS TO ZERO SO THAT WHILE THIS STATUS IS TRUE, GO TO THE NEXT ROW AND FETCH DATA
	FETCH NEXT FROM CURRENCY   --<< STEP 6: THIS WILL BRING THE NEXT ROW UNTIL IT REACHES THE LAST ROW IN THE TABLE

CLOSE CURRENCY  --<< CLOSE THE CURSOR

DEALLOCATE CURRENCY  --<< DISCONNECT FROM THE CURSOR


--EXAMPLE 2:  SETTING UP AND USING VARIBLE FOR THE OUTPUT OF A CURSOR

DECLARE @CurrencyCode NVARCHAR(3)  --<< STEP 1: DECLARE VARIABLES WITH DATATYPE FOR EACH COLUMN
DECLARE @Name NVARCHAR(50)
DECLARE @Modifieddate DATETIME


DECLARE CURRENCY CURSOR 


FOR SELECT  [CurrencyCode],[Name],[ModifiedDate]  
    FROM [AdventureWorks2014].[Sales].[Currency]

OPEN CURRENCY   

	FETCH NEXT FROM CURRENCY   
	INTO @CurrencyCode,@Name,@Modifieddate  --<< STEP 2:  INSERT THE DATA INTO VARIABLES

	BEGIN   --<< STEP 3: USE THE BLOCK BEGIN AND END STATMENTS TO EXECUTE THE WHILE

		PRINT 'THIS IS ONE WAY OF SHOWING THE DATA WITHIN THE VARIABLE:' + @CurrencyCode + ', ' +  @Name + ', ' +   CONVERT(CHAR(10),@Modifieddate,101)

		WHILE @@FETCH_STATUS  = 0  
		FETCH NEXT FROM CURRENCY   
		INTO @CurrencyCode,@Name,@Modifieddate  --<< STEP 4: INSERT THE DATA INTO VARIABLES

		PRINT 'THIS IS ONE WAY OF SHOWING THE DATA WITHIN THE VARIABLE:' + @CurrencyCode + ', ' +  @Name + ', ' +   CONVERT(CHAR(10),@Modifieddate,101)

	END

CLOSE CURRENCY  

DEALLOCATE CURRENCY  
